version: "3"

volumes:
  postgres-data:
    driver: local

services:
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  users-api:
    container_name: users-api
    build: .
    ports:
      - 3050:3050
    environment:
      - PORT=3050
      - POSTGRES_DSN=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
